# Generated by Django 5.0.6 on 2024-06-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('Cedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Fecha_nac', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('peso', models.CharField(max_length=3)),
                ('Genero', models.BooleanField(blank=True, default=True, null=True, verbose_name='masculino')),
                ('Estatura', models.CharField(max_length=3)),
            ],
        ),
    ]
